# Generated by Django 5.2.7 on 2025-10-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_name', models.CharField(max_length=50)),
                ('char_race', models.CharField(max_length=50)),
                ('char_class', models.CharField(max_length=50)),
                ('char_align', models.CharField(max_length=50)),
                ('char_str', models.IntegerField()),
                ('char_dex', models.IntegerField()),
                ('char_con', models.IntegerField()),
                ('char_wis', models.IntegerField()),
                ('char_int', models.IntegerField()),
                ('char_cha', models.IntegerField()),
                ('char_desc', models.TextField(blank=True)),
            ],
        ),
    ]
